### ISSUE TITLE
Options to leave ports 80/443 free for other use?

### ISSUE THREAD

**Issue by jlblancoc** [Shippable/admiral#1085]
Hi all, 

Currently, these ports:
```
80: internal gitlab server api endpoint
443: internal gitlab server secure api endpoint
```
are bound to the gitlab instance. I am interested in moving it to use other pair of ports so 80/443 remain free for other use in the machine, just like its port `22` is currently being redirected.

I have tried to launch the gitlab docker image with parameter `-p 50080:80` and indeed the port is remapped, but I'm afraid that's not enough because the port numbers `80` (and `443`?) seem to be hardwired and/or in internal configuration files inside other docker images. 

Do you have some instructions to allow gitlab to run on other port numbers in a reliable way?

Thanks.

**Comment by ric03uec** [comment]
@jlblancoc we'll actually be getting rid of gitlab shortly as a dependency which will free up all the ports required by it.
unfortunately, we don't have a straighforward way to disable/remap these ports right now. I'll be happy to jump on a call to discuss how we can do this.

**Comment by jlblancoc** [comment]
> we'll actually be getting rid of gitlab shortly as a dependency

That will be great! If this will be done within 1-2 months, I will rather just wait for the next release to be published instead of getting into the troubles of port remapping.

Thanks for the feedback!

**Comment by jlblancoc** [comment]
Hi, I saw a few new releases, but couldn't find changelogs... any news on the feature discussed above? Thanks

**Comment by ric03uec** [comment]
@jlblancoc we do a release every week and the changelog is available here: https://github.com/Shippable/support/wiki. we'll soon be providing a link to this in the product itself
- wrt the earlier discussion, we havent had a chance to remove gitlab dependency yet and the timeline for this is uncertain at this point. We're working on some high priority issues because of which this got pushed back.
- you can still go ahead and install shippable using admiral and we can help you out with remapping the ports and get the setup working. once we're done with gitlab dependency removal, you'll be able to migrate your existing data using the scripts we provide
hope this helps

**Comment by jlblancoc** [comment]
> you can still go ahead and install shippable using admiral and we can help you out with remapping the ports and get the setup working.

Sounds good to me! 

@ric03uec  Shall I ask you via Slack, or can I post my questions for port remapping directly here?

**Comment by ttrahan** [comment]
hi @jlblancoc: I've re-opened the Slack channel. Can you still access it?

**Comment by a-murphy** [comment]
Shippable Server can now be installed without GitLab.  The alternatives are to store state in S3 or to run without state (if you are planning to only use runSh jobs).
