### ISSUE TITLE
9817.2 user should be able to log in to admiral using new UI

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#1556]
- https://github.com/Shippable/pm/issues/9817
- bugs in existing login flow
    - log in screen does not work on pressing `enter` button. user should be able to press enter and log in 
    - logging in from the new login page should open the new dashboard. right now it opens old dashboard

**Comment by priyakirankumar** [comment]
@ric03uec I have fixed the issue of login screen not working on enter button, I will send the PR once you let me know about this PR (https://github.com/Shippable/admiral/pull/1553) because those changes are getting added while creating this PR.

As far as logging in to the new dashboard after login, it looks like the authorization is being done at the web server level and if the login token is not present it gets directed to loginCtrl. My guess is that the URL needs to be sent along from there but I do not know enough of the application/webserver setup or how the authorization is done so will not be able to do this.

**Comment by ric03uec** [comment]
can you resend the pr

**Comment by priyakirankumar** [comment]
Verified the first bit of "press enter and log in" on RC.

Closing this ticket for now, as the redirect to the new URL after Login will be handled later.
