### ISSUE TITLE
[bug] subs sync doesnt work after logging in

### ISSUE THREAD

**Issue by ric03uec** [Shippable/admiral#1720]
- https://github.com/Shippable/pm/issues/9817
- I could not sync my subscription after logging in.

**Comment by mohit5it9** [comment]
tested 3-4 times. On doing a fresh install:
 - initializing the infrastructure
 - installing all the configs and services

then logged in to WWW app. sync is happening correctly. also ran a few builds and they were also successful.
probably the error that @ambarish2012 saw was because of this fact:
before sync completed, he went on to the integrations page. there we attempt to get the subscriptions also. maybe as sync was not completed then, we get that error:

![anim](https://user-images.githubusercontent.com/11424742/35266509-849e465e-0049-11e8-8d15-d4d179be3e75.gif)

after sync completes, the user's subscription were successfully shown in the UI

**Comment by mohit5it9** [comment]
closing for now. will reopen in case it happens again
