### ISSUE TITLE
Python 3.6 does not exist

### ISSUE THREAD

**Issue by zixia** [Shippable/admiral#2215]
My shippable.yml: https://github.com/zixia/blinder/blob/dae071d71b407b9e23d5d84c478f543c19974132/shippable.yml
```yaml
language: python
python:
  - 3.6
```

The Shippable error message on web(console)
https://app.shippable.com/github/zixia/blinder/runs/47/1/console

```shell
  setup_ve 5s
  virtualenv -p /usr/bin/python3.6 /root/venv/3.6 4s  
The executable /usr/bin/python3.6 (from --python=/usr/bin/python3.6) does not exist
```

**Comment by trriplejay** [comment]
HI @zixia . The machine image you're using only has up to python 3.5.  You can see the details here: http://docs.shippable.com/platform/runtime/machine-image/ami-stable/

I'd recommend switching to the latest machine image so that you get all of the latest packages.  That should be v6.2.4, This will have python 3.6

You can change this by going to your subscription dashboard -> settings -> node pools -> click "edit" in your default node pool panel -> in the "Runtime Version" section, pick 6.2.4 from the dropdown -> click save.

let me know if you have any questions.

Also, in the future i'd recommend opening issues in our official support repository here: https://github.com/Shippable/support/issues  as they will be more visible to customer support.

thanks!

**Comment by zixia** [comment]
@trriplejay Thanks for your quick reply and warm-hearted help!

I just had found the `node pools` settings and changed the Runtime Version to 6.2.4 and Python 3.6 finally works like a charm!

I'll go to the support to post issues in the future. I posted here because it seems more like a technology problem.

However, it's just a misconfigured setting in my project. I don't know why my setting is a deprecated "STABLE" runtime, and the _subscription dashboard_ is hidden too deeply... I try my best but cost me about 10 minutes to figure out where it is.

**Comment by trriplejay** [comment]
I agree the ability to change versions is buried under quite a few pages and clicks. typically when a user first signs up for shippable, they'll be assigned a version (whatever is the latest/default at the time) and then as we release newer versions, we don't automatically move users forward, since that would risk breaking their builds as packages change.  I would guess that you had previously signed up or logged into shippable when "stable" was the latest version we had, and that's why you still have it today.

anyway, I'm glad you got it working. thanks for giving us a try!
