### ISSUE TITLE
8413.1 Create DB user and roles from Admiral machine

### ISSUE THREAD

**Issue by stephanielingwood** [Shippable/admiral#469]
https://github.com/Shippable/pm/issues/8413

Run psql commands from the Admiral machine to create the database user, roles, ...

**Comment by ric03uec** [comment]
- running these commands via psql will not give any additional functionality unless we use the same commands for the db running in a container too
- since the db running in a container is using a completely different method of initializing the db roles, users etc, we don't need to make the changes in the script that installs db on remote box
- closing this. we'll address this issue if we want to run the same commands for pg container as well as remote box
